# Copyright (c) 2026, alltechvirtual.com and contributors
"""One-way master-data seeding: staging -> a fresh ERPNext instance.

READ-ONLY against this site. Every frappe call here is a read; nothing is
written locally. All writes go over REST to the target.

Design notes that matter:

  * Records are read with get_doc(), not get_all(fields=["*"]). get_all returns
    parent fields only, which would ship Contacts and Addresses with an empty
    `links` table - i.e. attached to nothing.

  * Tree doctypes are ordered by `lft` so a parent always exists before its
    children. Warehouse, Item Group, Territory, Customer Group and Supplier
    Group are all trees.

  * Fields are intersected against the TARGET's schema up front rather than
    discovered by trial and error, so a staging-only custom field is dropped
    before the POST instead of after a failed one.

  * `name` is preserved. Link integrity depends on it: Item Price points at
    Item by name, Warehouse at its parent, Item at its Item Group. Where the
    target autonames from a field this is a no-op; where it would autoname by
    series, run set_target_naming() first.
"""

import json
import sys
import time
from urllib.parse import quote

import frappe
import requests

TARGET = "http://38.242.156.121:8000"
TOKEN = "33c865dda054429:d86c1905839a6df"
HEADERS = {
    "Authorization": f"token {TOKEN}",
    "Content-Type": "application/json",
    "Accept": "application/json",
}
TIMEOUT = 45

# Order matters: each depends on the ones above it.
#
# Warehouse Type is deliberately FIRST, ahead of Company. Creating a Company
# makes its default warehouses, and those require Warehouse Type "Transit" to
# already exist - with Company first, every company insert fails on
# "Could not find Warehouse Type: Transit".
DOCTYPES = [
    "Warehouse Type",
    "Company",
    "Warehouse",
    "UOM",
    "Item Group",
    "Brand",
    "Item",
    "Customer Group",
    "Territory",
    "Customer",
    "Supplier Group",
    "Supplier",
    "Contact",
    "Address",
    "Price List",
    "Item Price",
]

TREE_DOCTYPES = {
    "Company", "Warehouse", "Item Group", "Territory", "Customer Group", "Supplier Group",
}

# Link targets that cannot exist at the moment their parent is created.
#
# A Company's chart of accounts is generated BY the company insert, so every
# default_*_account on the record refers to something that does not exist yet -
# ERPNext rejects the whole document with LinkValidationError. Same story for
# default warehouses, which we transfer after companies.
#
# So we create the record without them and PUT them back in finalize(), once
# the things they point at are real.
DEFERRED_LINK_TARGETS = {
    "Account", "Cost Center", "Warehouse", "Letter Head", "Holiday List",
    "Terms and Conditions", "Finance Book", "Payment Terms Template",
    "Mode of Payment", "Item", "Price List", "Supplier", "Customer",
}
DEFER_ON_CREATE = {"Company"}

# Never shipped: audit metadata, and tree pointers the target recomputes.
SYSTEM_FIELDS = {
    "owner", "creation", "modified", "modified_by", "docstatus", "idx",
    "_user_tags", "_comments", "_assign", "_liked_by", "_seen",
    "doctype", "lft", "rgt", "old_parent",
}
CHILD_STRIP = {
    "owner", "creation", "modified", "modified_by", "docstatus",
    "parent", "parentfield", "parenttype", "name", "doctype",
    "_user_tags", "_comments", "_assign", "_liked_by",
}

_target_fields = {}


# ---------------------------------------------------------------------------
# Target schema
# ---------------------------------------------------------------------------


def target_fields(doctype):
    """Fieldnames the target actually has, so staging-only fields are dropped."""
    if doctype in _target_fields:
        return _target_fields[doctype]

    allowed = set(SYSTEM_FIELDS) | {"name", "parent", "parentfield", "parenttype", "idx"}
    try:
        r = requests.get(
            f"{TARGET}/api/resource/DocType/{quote(doctype, safe='')}",
            headers=HEADERS, timeout=TIMEOUT,
        )
        if r.status_code == 200:
            data = r.json().get("data", {})
            for f in data.get("fields", []):
                if f.get("fieldname"):
                    allowed.add(f["fieldname"])
        # Custom Fields live outside the DocType record.
        rc = requests.get(
            f"{TARGET}/api/resource/Custom Field"
            f"?filters=[[\"dt\",\"=\",\"{doctype}\"]]&fields=[\"fieldname\"]&limit_page_length=0",
            headers=HEADERS, timeout=TIMEOUT,
        )
        if rc.status_code == 200:
            for f in rc.json().get("data", []):
                if f.get("fieldname"):
                    allowed.add(f["fieldname"])
    except Exception as e:
        print(f"    ! could not read target schema for {doctype}: {str(e)[:100]}")

    _target_fields[doctype] = allowed
    return allowed


# Names that exist on the target, per doctype. Populated lazily and dropped
# after each doctype transfer so later records see what earlier ones created.
_index = {}

# Beyond this many records we stop validating against that doctype - the list
# fetch stops being worth it and the links are almost certainly fine.
INDEX_CAP = 20000


def target_names(doctype):
    if doctype in _index:
        return _index[doctype]
    names = set()
    try:
        r = requests.get(
            f"{TARGET}/api/resource/{quote(doctype, safe='')}"
            "?fields=[\"name\"]&limit_page_length=0",
            headers=HEADERS, timeout=TIMEOUT * 2,
        )
        if r.status_code == 200:
            rows = r.json().get("data", [])
            if len(rows) < INDEX_CAP:
                names = {row["name"] for row in rows}
    except Exception:
        pass
    _index[doctype] = names
    return names


def invalidate(doctype=None):
    if doctype:
        _index.pop(doctype, None)
    else:
        _index.clear()


def link_is_resolvable(link_doctype, value):
    """Whether a Link value exists on the target.

    Staging carries a bespoke chart of accounts, cost centres and letter heads
    that a fresh instance has never heard of. Sending those references makes
    ERPNext reject the ENTIRE document, so one unknown account costs us the
    whole warehouse or item. Dropping just the offending field keeps the
    record.
    """
    if not link_doctype or value in (None, ""):
        return True
    names = target_names(link_doctype)
    if not names:  # unknown / too large to index - don't block on it
        return True
    return value in names


def child_doctype_of(parent_doctype, fieldname):
    meta = frappe.get_meta(parent_doctype)
    df = meta.get_field(fieldname)
    return df.options if df and df.fieldtype in ("Table", "Table MultiSelect") else None


def deferred_fields(doctype):
    """Link fields on this doctype whose targets cannot exist at create time."""
    if doctype not in DEFER_ON_CREATE:
        return set()

    def _compute():
        meta = frappe.get_meta(doctype)
        return {
            df.fieldname
            for df in meta.fields
            if df.fieldtype == "Link" and df.options in DEFERRED_LINK_TARGETS
        }

    return _compute()


def clean(doc_dict, doctype, skip=None):
    """Filter a source document down to fields the target will accept."""
    allowed = target_fields(doctype)
    skip = skip or set()
    out = {}
    meta = frappe.get_meta(doctype)

    for key, value in doc_dict.items():
        if key in SYSTEM_FIELDS and key != "name":
            continue
        if key not in allowed or key in skip:
            continue
        if value in (None, ""):
            continue

        if isinstance(value, list) and value and isinstance(value[0], dict):
            child_dt = child_doctype_of(doctype, key)
            if not child_dt:
                continue
            child_allowed = target_fields(child_dt)
            child_meta = frappe.get_meta(child_dt)
            rows = []
            for row in value:
                clean_row = {}
                for k, v in row.items():
                    if k in CHILD_STRIP or k not in child_allowed or v in (None, ""):
                        continue
                    df = child_meta.get_field(k)
                    if df and df.fieldtype == "Link" and not link_is_resolvable(df.options, v):
                        continue
                    clean_row[k] = v
                # Dropping an unresolvable link can leave a child row missing a
                # field the target requires, which fails the whole parent with
                # a MandatoryError. A partial row carries no useful information
                # anyway, so drop the row rather than the document.
                required = [
                    df.fieldname for df in child_meta.fields
                    if df.reqd and df.fieldtype not in ("Section Break", "Column Break")
                ]
                if clean_row and all(clean_row.get(f) for f in required):
                    rows.append(clean_row)
            if rows:
                out[key] = rows
        else:
            df = meta.get_field(key)
            if df and df.fieldtype == "Link" and not link_is_resolvable(df.options, value):
                continue
            out[key] = value
    return out


# ---------------------------------------------------------------------------
# Target IO
# ---------------------------------------------------------------------------


def exists(doctype, name):
    try:
        r = requests.get(
            f"{TARGET}/api/resource/{quote(doctype, safe='')}/{quote(str(name), safe='')}",
            headers=HEADERS, timeout=TIMEOUT,
        )
        return r.status_code == 200
    except Exception:
        return False


def _error_text(response):
    try:
        payload = response.json()
    except Exception:
        return (response.text or "")[:400]
    for key in ("exception", "_server_messages", "message", "exc"):
        if payload.get(key):
            return str(payload[key])[:400]
    return json.dumps(payload)[:400]


def create(doctype, payload, retries=3):
    """POST one record, dropping fields the target rejects and retrying."""
    body = dict(payload)
    last = ""

    for _ in range(retries):
        try:
            r = requests.post(
                f"{TARGET}/api/resource/{quote(doctype, safe='')}",
                headers=HEADERS, data=json.dumps(body, default=str), timeout=TIMEOUT,
            )
        except Exception as e:
            return False, f"network: {str(e)[:200]}"

        if r.status_code in (200, 201):
            return True, None

        last = _error_text(r)

        # "Unknown column 'x'" / "has no attribute 'x'" -> drop that field, retry.
        dropped = None
        for token in ("Unknown column '", "no attribute '", "Invalid fieldname '"):
            if token in last:
                candidate = last.split(token, 1)[1].split("'", 1)[0]
                if candidate in body:
                    dropped = candidate
                    break
        if dropped:
            body.pop(dropped, None)
            continue
        break

    return False, last


# ---------------------------------------------------------------------------
# Source read
# ---------------------------------------------------------------------------


def source_records(doctype):
    """Names in dependency-safe order (parents first for trees)."""
    if doctype in TREE_DOCTYPES:
        return frappe.get_all(doctype, pluck="name", order_by="lft asc")
    if doctype == "Item":
        return frappe.get_all(doctype, pluck="name", order_by="creation asc")
    return frappe.get_all(doctype, pluck="name", order_by="creation asc")


def transfer(doctype, limit=None, verbose=False):
    names = source_records(doctype)
    if limit:
        names = names[:limit]

    created = skipped = failed = 0
    errors = []
    started = time.time()

    for i, name in enumerate(names, 1):
        if exists(doctype, name):
            skipped += 1
            continue
        try:
            doc = frappe.get_doc(doctype, name).as_dict()
        except Exception as e:
            failed += 1
            errors.append((name, f"read failed: {str(e)[:150]}"))
            continue

        ok, err = create(doctype, clean(doc, doctype, skip=deferred_fields(doctype)))
        if ok:
            created += 1
            if verbose:
                print(f"    + {name}")
        else:
            failed += 1
            errors.append((name, err))

        if i % 250 == 0:
            print(f"    ... {i}/{len(names)}  created={created} skipped={skipped} failed={failed}",
                  flush=True)

    elapsed = time.time() - started
    print(f"  {doctype:16} total={len(names):5} created={created:5} "
          f"skipped={skipped:5} failed={failed:5}  ({elapsed:.0f}s)", flush=True)

    for name, err in errors[:8]:
        print(f"      FAIL {name}: {err[:180]}")
    if len(errors) > 8:
        print(f"      ... and {len(errors) - 8} more failures")

    # Later doctypes must see what this one just created.
    invalidate(doctype)

    return {"doctype": doctype, "total": len(names), "created": created,
            "skipped": skipped, "failed": failed, "errors": errors}


# ---------------------------------------------------------------------------
# Target prep
# ---------------------------------------------------------------------------


def set_target_naming():
    """Make the target derive names from fields, not series.

    Without this the target mints its own Item names and the Item Price rows,
    which reference Items by name, all land on nothing.
    """
    updates = [
        ("Stock Settings", {"item_naming_by": "Item Code"}),
        ("Selling Settings", {"cust_master_name": "Customer Name"}),
        ("Buying Settings", {"supp_master_name": "Supplier Name"}),
    ]
    for doctype, values in updates:
        try:
            r = requests.put(
                f"{TARGET}/api/resource/{quote(doctype, safe='')}/{quote(doctype, safe='')}",
                headers=HEADERS, data=json.dumps(values), timeout=TIMEOUT,
            )
            print(f"  {doctype:18} {values} -> HTTP {r.status_code}")
        except Exception as e:
            print(f"  {doctype:18} FAILED: {str(e)[:150]}")


def finalize(doctype="Company"):
    """Second pass: PUT the fields we deferred at create time.

    Run this only after everything they reference exists - for Company that
    means after Warehouses, so at the very end of the transfer. Each field is
    sent individually so one unresolvable link cannot block the rest.
    """
    fields = deferred_fields(doctype)
    if not fields:
        return {}

    print(f"\n=== finalize {doctype}: restoring {len(fields)} deferred field(s) ===")
    applied = missing = 0

    for name in source_records(doctype):
        try:
            doc = frappe.get_doc(doctype, name).as_dict()
        except Exception:
            continue
        if not exists(doctype, name):
            continue

        allowed = target_fields(doctype)
        payload = {
            f: doc.get(f) for f in fields
            if doc.get(f) and f in allowed
        }
        if not payload:
            continue

        ok_fields = {}
        for field, value in payload.items():
            # Only set it if the referenced record actually landed.
            meta_field = frappe.get_meta(doctype).get_field(field)
            if meta_field and meta_field.options and not exists(meta_field.options, value):
                missing += 1
                continue
            ok_fields[field] = value

        if not ok_fields:
            continue

        try:
            r = requests.put(
                f"{TARGET}/api/resource/{quote(doctype, safe='')}/{quote(str(name), safe='')}",
                headers=HEADERS, data=json.dumps(ok_fields, default=str), timeout=TIMEOUT,
            )
            if r.status_code == 200:
                applied += len(ok_fields)
                print(f"  {name}: set {len(ok_fields)} field(s)")
            else:
                print(f"  {name}: HTTP {r.status_code} {_error_text(r)[:140]}")
        except Exception as e:
            print(f"  {name}: {str(e)[:140]}")

    print(f"  applied={applied} skipped_missing_target={missing}")
    return {"applied": applied, "missing": missing}


def run(doctypes=None, limit=None, verbose=False):
    doctypes = doctypes or DOCTYPES
    results = []
    for dt in doctypes:
        results.append(transfer(dt, limit=limit, verbose=verbose))

    print("\n" + "=" * 74)
    print(f"{'Doctype':18}{'Total':>8}{'Created':>9}{'Skipped':>9}{'Failed':>8}")
    print("-" * 74)
    tot = dict(total=0, created=0, skipped=0, failed=0)
    for r in results:
        print(f"{r['doctype']:18}{r['total']:>8}{r['created']:>9}{r['skipped']:>9}{r['failed']:>8}")
        for k in tot:
            tot[k] += r[k]
    print("-" * 74)
    print(f"{'TOTAL':18}{tot['total']:>8}{tot['created']:>9}{tot['skipped']:>9}{tot['failed']:>8}")
    return results
